name: Build, Analyze, Scan

on: 
    push:
        branches:
            - main

jobs:
    build_analyze_scan:
        name: Build
        runs-on: ubuntu-latest    #[self-hosted]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v3  # Consider upgrading to v3
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Docker Build and Push
              run: |
                  docker-compose -f docker-compose.yml build
                  docker tag webapp:latest vaishnavk1114/webapp:latest
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker push vaishnavk1114/webapp:latest
              env:
                DOCKER_CLI_EXPERIMENTAL: 1  # Optional: Enable experimental Docker features
